<?php

declare(strict_types=1);

namespace Phlix\Hub\Http\Controllers;

use Phlix\Hub\Auth\AuthManager;
use Phlix\Hub\Common\WebPortal\PageRenderer;
use Phlix\Hub\Hub\ServerInfoHandler;
use Phlix\Hub\Http\Request;
use Phlix\Hub\Http\Response;

/**
 * SSR page controller — serves the Smarty templates that back
 * `GET /signup`, `GET /login`, `GET /my-servers`, and `GET /claim-server`.
 *
 * Each invocation reads `$request->path` and dispatches to the matching
 * template render. Keeping this single-class-many-actions shape lets
 * us register one controller with the {@see \Phlix\Hub\Http\Router} per
 * path while keeping per-template assigns close together.
 *
 * @package Phlix\Hub\Http\Controllers
 * @since 0.2.0
 */
final class PageController
{
    /**
     * @param PageRenderer     $renderer    Smarty wrapper.
     * @param AuthManager      $auth        Used to load the user record on protected pages.
     * @param ServerInfoHandler $serverInfo Used to fetch the user's servers for the dashboard.
     */
    public function __construct(
        private readonly PageRenderer $renderer,
        private readonly AuthManager $auth,
        private readonly ServerInfoHandler $serverInfo,
    ) {
    }

    /**
     * Dispatch based on `$request->path`.
     */
    public function __invoke(Request $request): Response
    {
        return match (true) {
            $request->path === '/signup'         => $this->signup($request),
            $request->path === '/login'          => $this->login($request),
            $request->path === '/my-servers'     => $this->myServers($request),
            $request->path === '/claim-server'   => $this->claimServer($request),
            $request->path === '/requests'       => $this->requests($request),
            $request->path === '/admin/requests' => $this->adminRequests($request),
            $request->path === '/'               => $this->home($request),
            default => (new Response())->status(404)->html('<h1>Not Found</h1>'),
        };
    }

    /**
     * `GET /` — landing page.
     */
    public function home(Request $request): Response
    {
        $html = $this->renderer->render('home/index.tpl', [
            'is_authenticated' => $request->userId !== null,
        ]);
        return (new Response())->html($html);
    }

    /**
     * `GET /signup` — render the signup form.
     */
    public function signup(Request $request): Response
    {
        $html = $this->renderer->render('auth/signup.tpl', [
            'username' => '',
            'email'    => '',
        ]);
        return (new Response())->html($html);
    }

    /**
     * `GET /login` — render the login form.
     */
    public function login(Request $request): Response
    {
        $html = $this->renderer->render('auth/login.tpl', [
            'username' => '',
        ]);
        return (new Response())->html($html);
    }

    /**
     * `GET /my-servers` — dashboard showing the user's claimed servers.
     *
     * The `servers` key is populated by fetching from ServerInfoHandler.
     * The template loops over `$servers` to render individual server cards.
     *
     * @param array<string, mixed> $servers Pre-fetched server list (optional, injected by router).
     */
    public function myServers(Request $request, array $servers = []): Response
    {
        $userId = $request->userId ?? '';

        if ($servers === [] && $userId !== '') {
            $dtos = $this->serverInfo->getServersForUser($userId);
            $servers = array_map(fn ($dto) => $dto->toPayload(), $dtos);
        }

        $user = $this->auth->getCurrentUser($userId);
        $html = $this->renderer->render('home/my-servers.tpl', [
            'user'    => $user ?? [],
            'servers' => $servers,
        ]);
        return (new Response())->html($html);
    }

    /**
     * `GET /claim-server` — page with a form to claim a new server
     * using a claim code generated by the server's pairing flow.
     */
    public function claimServer(Request $request): Response
    {
        $html = $this->renderer->render('home/claim-server.tpl', []);
        return (new Response())->html($html);
    }

    /**
     * `GET /requests` — user "Request media" SSR page (K.3, moved to hub).
     */
    public function requests(Request $request): Response
    {
        $html = $this->renderer->render('home/requests.tpl', [
            'is_authenticated' => $request->userId !== null,
        ]);
        return (new Response())->html($html);
    }

    /**
     * `GET /admin/requests` — admin request queue SSR page (K.3, hub).
     */
    public function adminRequests(Request $request): Response
    {
        $html = $this->renderer->render('home/admin-requests.tpl', [
            'is_authenticated' => $request->userId !== null,
        ]);
        return (new Response())->html($html);
    }
}
