-- migration: 046_federation_peer_leaf_hub_id
-- C-1(3): reconciles the two federation id spaces. A peer row's `id` is
-- generated by the hub that CREATES the row, but a connecting leaf dials
-- `/relay/federation/{its own federation_hubs.id}`. Without a second
-- identity column the master can never resolve that path segment to the
-- peer row, so fresh links can never bootstrap or reconnect.
--
-- `leaf_hub_id` stores the peer hub's OWN federation_hubs.id as reported
-- by itself (via HUB_HELLO on the master side, via HELLO_ACK's
-- master_hub_id on the leaf side). FederationHubRepository::getPeerById()
-- matches either `id` OR `leaf_hub_id`, making both dial forms valid.
--
-- Nullable + unique: NULL until the identity is observed/bound; MySQL
-- permits multiple NULLs in a UNIQUE index, so unbound peers coexist.
--
-- Idempotency: the runner records applied files in the `migrations`
-- tracking table and never re-runs them, so a plain ALTER suffices.
-- (MySQL 8 does not support `ADD COLUMN IF NOT EXISTS` — MariaDB-only.)

ALTER TABLE federation_peers
    ADD COLUMN leaf_hub_id CHAR(36) NULL AFTER public_key,
    ADD UNIQUE KEY uq_federation_peers_leaf_hub_id (leaf_hub_id);
