#!/bin/sh
set -e

# ============================================================================
# Phlix Hub — container entry point (S300).
# ============================================================================
# Apply database migrations, then BECOME the Workerman daemon.
#
# ⚠ THIS FILE IS THE IMAGE'S `CMD`, and until S300 it had never run.
# `Dockerfile`'s CMD names `/docker-entrypoint.sh` while `COPY . /var/www/html/`
# lands this script at /var/www/html/docker/docker-entrypoint.sh, so every
# container built from that Dockerfile exited 2 with
# "sh: can't open '/docker-entrypoint.sh'" before executing a single line below.
# The matching `COPY docker/docker-entrypoint.sh /docker-entrypoint.sh` is now
# in the Dockerfile and tests/Unit/Docker/DockerImageContractTest.php asserts
# the pair. `docker build` never executes CMD, which is why
# `scripts/docker-boot-smoke.sh` (the boot gate) exists.
#
# Two more things this script used to get wrong, both fixed below:
#
#   * it gated migrations on `PHLIX_DATABASE_HOST` — a variable NO php in this
#     repository reads. config/database.php reads `HUB_DB_HOST` / `HUB_DB_PORT`
#     / `HUB_DB_USER` / `HUB_DB_PASSWORD` / `HUB_DB_NAME`. A correctly
#     configured hub container would therefore have skipped migrations
#     silently; a container configured with the phlix-server names would have
#     run them against the `127.0.0.1/phlix_hub` defaults;
#   * it exec'd `php /var/www/html/public/index.php start`. **public/index.php
#     does not exist in this repository.** The daemon is `start.php`
#     (`Worker::runAll()`), the same file systemd runs on a real box.
#
# NO SUPERVISORD. phlix-server needs one because its image runs a process
# manager whose FATAL has to be translated into a container exit code; the hub
# image runs exactly one process, so `exec`ing it makes the Workerman master
# PID 1 and the container's exit code IS the daemon's exit code. A dead daemon
# is a dead container, with no listener, no marker file and no
# `Up`-while-serving-nothing state to defend against.
#
# PHLIX_HUB_APP_ROOT exists so this script can be smoke-tested end to end
# outside an image; the default is the image's real path.
# ============================================================================

APP_ROOT="${PHLIX_HUB_APP_ROOT:-/var/www/html}"
JWT_SECRET_FILE="${PHLIX_HUB_JWT_SECRET_FILE:-/var/phlix/config/hub_jwt_secret}"

echo "Starting Phlix Hub..."

# Xdebug's trace directory (docker/php.ini sets xdebug.trace_output_dir).
mkdir -p /tmp/xdebug 2>/dev/null || true

# ---------------------------------------------------------------------------
# HUB_JWT_SECRET — a hard boot requirement outside dev.
#
# AuthServicesProvider::resolveSecret() throws MissingJwtSecretException unless
# HUB_JWT_SECRET (or auth.secret) is at least 32 bytes; the random per-process
# fallback is dev-only on purpose, because with HUB_WORKERS > 1 each worker
# would mint a DIFFERENT secret and authentication would fail intermittently.
#
# So `docker run` with no configuration would refuse to serve. Resolution order,
# most explicit first — mirroring phlix-server's entrypoint:
#   1. HUB_JWT_SECRET     — an operator configuring the app always wins.
#   2. $JWT_SECRET_FILE   — a secret generated by a PREVIOUS boot. It lives
#                           under /var/phlix/config, a persistent volume in the
#                           shipped deployments, so it survives restarts: a
#                           secret that changed each boot would invalidate every
#                           session.
#   3. generated here     — so a bare `docker run` works out of the box.
#
# Generation uses od(1)+/dev/urandom (busybox and coreutils both have it) rather
# than `php -r`, so it cannot depend on the application it is about to start.
# ---------------------------------------------------------------------------
hub_generate_secret() {
    if od -An -N32 -tx1 /dev/urandom 2>/dev/null | tr -d ' \n' | grep -qE '^[0-9a-f]{64}$'; then
        od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
        return 0
    fi
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return 0
    fi
    return 1
}

if [ -z "${HUB_JWT_SECRET:-}" ] && [ -r "$JWT_SECRET_FILE" ]; then
    HUB_JWT_SECRET="$(cat "$JWT_SECRET_FILE" 2>/dev/null || true)"
    [ -n "$HUB_JWT_SECRET" ] && echo "Using the JWT signing key persisted at ${JWT_SECRET_FILE}."
fi

if [ -z "${HUB_JWT_SECRET:-}" ]; then
    HUB_JWT_SECRET="$(hub_generate_secret 2>/dev/null || true)"
    if [ -z "$HUB_JWT_SECRET" ]; then
        echo "==========================================================" >&2
        echo "PHLIX-HUB-JWT-SECRET-UNAVAILABLE: could not generate a signing" >&2
        echo "key (no usable od(1)/openssl). Set HUB_JWT_SECRET explicitly —" >&2
        echo "the hub refuses to serve authenticated traffic without one." >&2
        echo "==========================================================" >&2
    elif ( umask 077 && printf '%s' "$HUB_JWT_SECRET" > "$JWT_SECRET_FILE" ) 2>/dev/null; then
        echo "Generated a JWT signing key and persisted it to ${JWT_SECRET_FILE}."
    else
        echo "==========================================================" >&2
        echo "PHLIX-HUB-JWT-SECRET-EPHEMERAL: generated a JWT signing key but" >&2
        echo "could not write ${JWT_SECRET_FILE}. It will CHANGE on every" >&2
        echo "restart, invalidating all sessions. Mount /var/phlix/config, or" >&2
        echo "set HUB_JWT_SECRET." >&2
        echo "==========================================================" >&2
    fi
fi

export HUB_JWT_SECRET

# `1`/`true`/`yes`/`on`, case-insensitive, whitespace-insensitive. The trim
# matters: a docker `env_file` preserves a trailing space, and
# `HUB_MIGRATIONS_STRICT="1 "` silently falling through to boot-anyway is
# exactly the kind of opt-in that looks applied and is not.
migrations_strict() {
    case "$(printf '%s' "${HUB_MIGRATIONS_STRICT:-}" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')" in
        1 | true | yes | on) return 0 ;;
        *) return 1 ;;
    esac
}

# ---------------------------------------------------------------------------
# Migrations. The banners are GREPPABLE and the boot gate reads them: /health
# is DB-free by design (HealthController touches neither DB nor filesystem), so
# "the app serves" cannot distinguish a migrated schema from no schema at all.
# phlix-server's gate measured exactly that — 114 connection refusals, a
# failure banner, and every assertion green.
#
# Default is to START ANYWAY on a failed migration (same decision as
# phlix-server's S159): a hub that crash-loops takes every enrolled server
# offline, while one on a partially-migrated schema is degraded but reachable
# and can say so. HUB_MIGRATIONS_STRICT=1 inverts that.
# ---------------------------------------------------------------------------
migrations_skipped_reason=''
if [ -z "${HUB_DB_HOST:-}" ]; then
    migrations_skipped_reason="no database host configured (set HUB_DB_HOST)"
elif [ ! -f "${APP_ROOT}/scripts/run-migrations.php" ]; then
    migrations_skipped_reason="${APP_ROOT}/scripts/run-migrations.php not found"
fi

if [ -n "$migrations_skipped_reason" ]; then
    echo "Skipping database migrations: ${migrations_skipped_reason}."
    if migrations_strict; then
        echo "==========================================================" >&2
        echo "PHLIX-HUB-MIGRATIONS-NOT-RUN: ${migrations_skipped_reason}." >&2
        echo "HUB_MIGRATIONS_STRICT is set and the schema could not be" >&2
        echo "verified: refusing to start." >&2
        echo "==========================================================" >&2
        exit 1
    fi
else
    echo "Running database migrations..."
    # `set -e` must not abort here: the exit code is inspected below.
    # `cmd || var=$?` is the POSIX-portable way to suppress `set -e` while
    # KEEPING the status. (`if ! cmd; then …; fi` also suppresses `set -e`, but
    # discards `$?`, which both the banner and strict mode need.)
    migration_status=0
    php "${APP_ROOT}/scripts/run-migrations.php" || migration_status=$?

    if [ "$migration_status" -ne 0 ]; then
        echo "==========================================================" >&2
        echo "PHLIX-HUB-MIGRATION-FAILURE: scripts/run-migrations.php exited ${migration_status}." >&2
        echo "The database schema may be HALF-MIGRATED. Failing migrations are" >&2
        echo "not recorded in schema_migrations and are retried on next boot." >&2
        echo "Run 'php scripts/run-migrations.php' (or 'bin/phlix migrate')" >&2
        echo "for the full error list." >&2

        if migrations_strict; then
            echo "HUB_MIGRATIONS_STRICT is set: refusing to start." >&2
            echo "==========================================================" >&2
            exit "$migration_status"
        fi

        echo "Starting anyway (default). Set HUB_MIGRATIONS_STRICT=1 to refuse" >&2
        echo "to start on a migration failure instead." >&2
        echo "==========================================================" >&2
    else
        # A POSITIVE marker, printed by this script and nothing else. The boot
        # gate greps for it: an absent failure banner is not evidence that the
        # migration step ran — the step could have been removed entirely.
        echo "PHLIX-HUB-MIGRATIONS-OK: scripts/run-migrations.php exited 0."
    fi
fi

# The daemon becomes PID 1: its exit code is the container's exit code, and
# `docker stop` reaches Workerman's own TERM handling directly.
exec php "${APP_ROOT}/start.php" start
